tasks:
- init: ./mvnw package -DskipTests
  command: java -jar target/*.jar

# exposed ports
ports:
- port: 8080
  onOpen: open-preview

vscode:
  extensions:
    - redhat.java
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-test
    - atomiks.moonlight
    - atomiks.moonlight
    - hediet.vscode-drawio
    - humao.rest-client
    - PKief.material-icon-theme
    - pnp.polacode
    - redhat.vscode-yaml
    - sandcastle.vscode-open
    - vscjava.vscode-java-pack
    - donjayamanne.githistory
    - theumletteam.umlet
